unique_ids:
  forms: {Home_Screen: LFKODCGRDKWUD2GTRDAQCRNLFDG7LHFP, Win_Screen: MYYZPOHKVUPJPANZWGHITNP423KKTKNF,
    Log_Screen: ZV2M5PFJEZQV72FEL2FGKFEXWB3LRLXW, Log_Screen.ItemTemplate2: NUMDNFFSGFXHJZ3WHVLTMJEJFYKNZKBX,
    Play_Screen: WUICOPOD3GU2DUFBROKWF2IQU7QQAEJN, score_board.RowTemplate2: KICSRD6WBKR4C5UM5URF2REPZG5OMBTH,
    replay_buttons: UUSVH4ZCR5XIXV4LUVLNM6OWACGL4FYO, score_board: VQ7XUJRB2BCKYPXB63UMVQEZZVICTMZ7,
    Lose_Screen: HQ7KZVEK5QY5IU3AFLNG2UYJ3QN5KXV6, Top_Ten: Q3R7EC5BXQSCRCBCTTVYFZEIYCXMDBRS,
    Lose_Screen.ItemTemplate1: LTVHGTPAZ7ZP5KWHL3XPHWQUSALLRZYS, Post_Win_Screen: 3JRR5U2BF5EDJJDQN5FXRKWKGWSCRNH4}
  modules: {Globals: QPNXPASFMPZLKNLFVP6QONXRQOPQQXSR}
  server_modules: {ServerModule1: OYUYUBTIK5GEY7X3B3SXZE5IMUTGZWXP}
  assets: {standard-page.html: 5W2ZA6QXGTGLBHG5YR3OYYPZDFWEOOZE, theme.css: JXLMXG4LDR4RRHHIVPKH26LVRCZLUHOX}
