unique_ids:
  forms: {Home_Screen: LFKODCGRDKWUD2GTRDAQCRNLFDG7LHFP, Win_Screen: MYYZPOHKVUPJPANZWGHITNP423KKTKNF,
    Log_Screen: CHG7X4GYCCKAO4P5KX7GELTHYUC2YHGC, Log_Screen.ItemTemplate2: 4IYYS5T2X6FKWBLTFFPKGUGQT6VUK6BW,
    Play_Screen: WUICOPOD3GU2DUFBROKWF2IQU7QQAEJN, score_board.RowTemplate2: 2EVMWVIBS25WZJACOXR7RI3JNTUEAFOI,
    replay_buttons: QFKHVVW4EKYDOVWKEDOEX3U2HNGZX5TL, score_board: ACJSL3HYRD2CILOC6DQUIM7LTKKERRDN,
    Lose_Screen: HQ7KZVEK5QY5IU3AFLNG2UYJ3QN5KXV6, Top_Ten: Q3R7EC5BXQSCRCBCTTVYFZEIYCXMDBRS,
    Lose_Screen.ItemTemplate1: LTVHGTPAZ7ZP5KWHL3XPHWQUSALLRZYS, Post_Win_Screen: IXVJF4PBA5EJ7JCJZAHYAJZFEWLV24J4}
  modules: {Globals: QPNXPASFMPZLKNLFVP6QONXRQOPQQXSR}
  server_modules: {ServerModule1: OYUYUBTIK5GEY7X3B3SXZE5IMUTGZWXP}
  assets: {standard-page.html: 5W2ZA6QXGTGLBHG5YR3OYYPZDFWEOOZE, theme.css: JXLMXG4LDR4RRHHIVPKH26LVRCZLUHOX}
