unique_ids:
  forms: {Home_Screen: LFKODCGRDKWUD2GTRDAQCRNLFDG7LHFP, Win_Screen: MYYZPOHKVUPJPANZWGHITNP423KKTKNF,
    Log_Screen: NJBBWTKWALDYNHWTW6XV4TYMX6RNZ5YK, Log_Screen.ItemTemplate2: WNDALSC74P6GYAMNXNKT5WIKGYLQTGHM,
    Play_Screen: WUICOPOD3GU2DUFBROKWF2IQU7QQAEJN, score_board.RowTemplate2: NI5PU2OV6EQSLPVFKHUQKBZQ5RFLNOLS,
    replay_buttons: OXZTOYSTY5ZKD4UGUUZU3WE5JNVBH4TR, score_board: WWNM77ZZNUJAGFEFTODLKABT5DLC3M2T,
    Lose_Screen: HQ7KZVEK5QY5IU3AFLNG2UYJ3QN5KXV6, Top_Ten: Q3R7EC5BXQSCRCBCTTVYFZEIYCXMDBRS,
    Lose_Screen.ItemTemplate1: LTVHGTPAZ7ZP5KWHL3XPHWQUSALLRZYS, Post_Win_Screen: VT367FMZTGGXALTDHPHWV3TH5DJ6N6D4}
  modules: {Globals: QPNXPASFMPZLKNLFVP6QONXRQOPQQXSR}
  server_modules: {ServerModule1: OYUYUBTIK5GEY7X3B3SXZE5IMUTGZWXP}
  assets: {standard-page.html: 5W2ZA6QXGTGLBHG5YR3OYYPZDFWEOOZE, theme.css: JXLMXG4LDR4RRHHIVPKH26LVRCZLUHOX}
