unique_ids:
  forms: {Homepage: LFKODCGRDKWUD2GTRDAQCRNLFDG7LHFP, Play_Screen: WUICOPOD3GU2DUFBROKWF2IQU7QQAEJN,
    Score_Screen: HQ7KZVEK5QY5IU3AFLNG2UYJ3QN5KXV6}
  modules: {Globals: QPNXPASFMPZLKNLFVP6QONXRQOPQQXSR}
  server_modules: {ServerModule1: OYUYUBTIK5GEY7X3B3SXZE5IMUTGZWXP}
  assets: {standard-page.html: 5W2ZA6QXGTGLBHG5YR3OYYPZDFWEOOZE, theme.css: JXLMXG4LDR4RRHHIVPKH26LVRCZLUHOX}
