unique_ids:
  forms: {Win_Screen: MYYZPOHKVUPJPANZWGHITNP423KKTKNF, Homepage: LFKODCGRDKWUD2GTRDAQCRNLFDG7LHFP,
    Play_Screen: WUICOPOD3GU2DUFBROKWF2IQU7QQAEJN, Lose_Screen: HQ7KZVEK5QY5IU3AFLNG2UYJ3QN5KXV6,
    Post_Win_Screen.RowTemplate1: XIGGOTGS5XCUUGHED4MGPFONOUN3PS5C, High_Scores: Q3R7EC5BXQSCRCBCTTVYFZEIYCXMDBRS,
    Post_Win_Screen.ItemTemplate2: 2ALWDVJE7KQUTBRLNCKXJHV4YOCR4X7U, Lose_Screen.ItemTemplate1: LTVHGTPAZ7ZP5KWHL3XPHWQUSALLRZYS,
    Post_Win_Screen: 34HTWVYU6ACOAD5KK45OZFZ6ODXRSDQ2}
  modules: {Globals: QPNXPASFMPZLKNLFVP6QONXRQOPQQXSR}
  server_modules: {ServerModule1: OYUYUBTIK5GEY7X3B3SXZE5IMUTGZWXP}
  assets: {standard-page.html: 5W2ZA6QXGTGLBHG5YR3OYYPZDFWEOOZE, theme.css: JXLMXG4LDR4RRHHIVPKH26LVRCZLUHOX}
