unique_ids:
  forms: {Home_Screen: LFKODCGRDKWUD2GTRDAQCRNLFDG7LHFP, Win_Screen: MYYZPOHKVUPJPANZWGHITNP423KKTKNF,
    Log_Screen: XZQ6ZGEKQP4DCGKQZGCV64LA4UKYBQ2O, Log_Screen.ItemTemplate2: 6WAHHBGYSLKHX7O6ZQFCKRZAHDUS7RYO,
    Play_Screen: WUICOPOD3GU2DUFBROKWF2IQU7QQAEJN, score_board.RowTemplate2: 2EVMWVIBS25WZJACOXR7RI3JNTUEAFOI,
    replay_buttons: 4RS7WEUJBQNOYSMIMVGYG2DUFLNZ4TEH, score_board: UGL34WRTGQ7F5NK7UHVET25K6E6ID67O,
    Lose_Screen: HQ7KZVEK5QY5IU3AFLNG2UYJ3QN5KXV6, Top_Ten: Q3R7EC5BXQSCRCBCTTVYFZEIYCXMDBRS,
    Lose_Screen.ItemTemplate1: LTVHGTPAZ7ZP5KWHL3XPHWQUSALLRZYS, Post_Win_Screen: VHSPRFCGIGVTJSPOHC22DCY4NYHRBGO6}
  modules: {Globals: QPNXPASFMPZLKNLFVP6QONXRQOPQQXSR}
  server_modules: {ServerModule1: OYUYUBTIK5GEY7X3B3SXZE5IMUTGZWXP}
  assets: {standard-page.html: 5W2ZA6QXGTGLBHG5YR3OYYPZDFWEOOZE, theme.css: JXLMXG4LDR4RRHHIVPKH26LVRCZLUHOX}
