unique_ids:
  forms: {High_Scores: Q3R7EC5BXQSCRCBCTTVYFZEIYCXMDBRS, Homepage: LFKODCGRDKWUD2GTRDAQCRNLFDG7LHFP,
    Lose_Screen: HQ7KZVEK5QY5IU3AFLNG2UYJ3QN5KXV6, Lose_Screen.ItemTemplate1: LTVHGTPAZ7ZP5KWHL3XPHWQUSALLRZYS,
    Play_Screen: WUICOPOD3GU2DUFBROKWF2IQU7QQAEJN, Win_Screen: K7PGU5DXMYYXPXNBM3TSPPFX5OTQE2BN}
  modules: {Globals: QPNXPASFMPZLKNLFVP6QONXRQOPQQXSR}
  server_modules: {ServerModule1: OYUYUBTIK5GEY7X3B3SXZE5IMUTGZWXP}
  assets: {standard-page.html: 5W2ZA6QXGTGLBHG5YR3OYYPZDFWEOOZE, theme.css: JXLMXG4LDR4RRHHIVPKH26LVRCZLUHOX}
